name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Login exitoso"

    - name: Build Docker Image
      run: |
        echo "Iniciando build"
        docker image build -t jun4ever/graphql-actions:0.0.2 .
        docker image build -t jun4ever/graphql-actions:latest .
        echo "Build exitoso"

    - name: Push Docker Image
      run: |
        echo "Iniciando push"
        docker push jun4ever/graphql-actions:0.0.2
        docker push jun4ever/graphql-actions:latest
        echo "Push exitoso"

        
        
    # - name: Build the Docker image
    # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
